### ISSUE TITLE
First visit search could do with some defaults

### ISSUE THREAD

**Issue by totaltrash** [ash-project/ash_hq#1]
Currently, your first visit to Ash HQ, you can search the documentation, but the search defaults to 'None' for the project versions:

![image](https://user-images.githubusercontent.com/637350/180947169-c4fab326-e67f-47e1-a170-374efc8dbfba.png)

It might make sense to default Ash to the current version?

Note, you can't replicate this with a private window (something must be shared between a private window and a previous non private session)

**Comment by zachdaniel** [comment]
Alright, now we default to the latest version of Ash, and for the rest we default to None
