### ISSUE TITLE
Search results for DSL items are missing breadcrumb info

### ISSUE THREAD

**Issue by sevenseacat** [ash-project/ash_hq#106]
**Brief Description**

After the move to have all nested DSL items on one page, searching for them leads to some odd results with breadcrumbs.

**Steps to reproduce the bug**

* Click search bar
* Search for a DSL item such as `identities`
* The first results (as seen below) are for DSL items in the Ash.Resource DSL, as expected, but the breadcrumb info is missing.

**Context**

<img width="733" alt="Screenshot 2023-02-22 at 9 08 00 am" src="https://user-images.githubusercontent.com/543859/220494641-6ca0eec8-b152-4957-813e-d75edfbea45f.png">

**Comment by zachdaniel** [comment]
Ah, yeah I know exactly how I broke this.

**Comment by zachdaniel** [comment]
Deploying the fix now.

**Comment by zachdaniel** [comment]
Thanks for the report!
