### ISSUE TITLE
Links to DSL items from guides are now 404s

### ISSUE THREAD

**Issue by sevenseacat** [ash-project/ash_hq#107]
**Brief Description**

Another casualty of moving all of the DSL items to one page? I just noticed this when reading the aggregates guide.

**Steps to reproduce the bug**

* Read the Aggregates guide - https://ash-hq.org/docs/guides/ash/latest/topics/aggregates
* The link to read more in "See the docs on [Ash.Resource.Dsl.aggregates](http://ash-hq.org/docs/dsl/ash/latest/ash-resource-dsl/aggregates) for more information." is a 404 - correct URL is now https://ash-hq.org/docs/dsl/ash-resource#aggregates .

**Comment by zachdaniel** [comment]
Interesting...I probably just need to reimport docs?

**Comment by zachdaniel** [comment]
Actually we need those links to keep working. I added a forwarding endpoint for them, but must have missed something.

**Comment by zachdaniel** [comment]
As always, thanks for the quick report and reproduction steps 🙇. A fix is going out now.
