### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by DaniruKun** [ash-project/ash_hq#109]
**Show where you found the issue**
https://ash-hq.org/docs/guides/ash_phoenix/latest/tutorials/getting-started-with-ash-and-phoenix#continue-learning

**Share the problematic documentation**
[Read more about how to query the data in your resources.](https://ash-hq.org/documentation/module/ash/ash-query) is a dead link.

**Comment by zachdaniel** [comment]
Thank you for the report! I've fixed the link and it will update on the next release of the package.
