### ISSUE TITLE
:let added in v0.18 of LiveView

### ISSUE THREAD

**Issue by Essstp** [ash-project/ash_hq#114]
Get Started with Ash and Phoenix --> Connecting your Resource to a Phoenix LiveView.

`<.form let={f} for={@create_form} phx-submit="create_post">` 

and 

`<.form let={f} for={@update_form} phx-submit="update_post">`

:let was introduced in v0.18, so I needed to add the colon to get this example working.

**Comment by zachdaniel** [comment]
Fixed in latest docs, will deploy :)
