### ISSUE TITLE
Top nav bar doesn't display when going direct to a link with fragment

### ISSUE THREAD

**Issue by totaltrash** [ash-project/ash_hq#14]
When going to ash-hq via a link with a fragment, I've noticed the top nav bar (with the 'search documentation' etc) disappears. It looks like it appears on the disconnected mount, then disappears on the connected mount?

Tested on Chrome (on linux):

* Click this: https://ash-hq.org/docs/guides/ash/latest/topics/actions.md#create-update-destroy-actions
* Scroll to top
* No nav bar (and no way to scroll up to it with page up etc):

![image](https://user-images.githubusercontent.com/637350/188769281-88e59891-f423-422e-8cb3-32a38d8070a1.png)

**Comment by zachdaniel** [comment]
what on earth

**Comment by zachdaniel** [comment]
Okay, fixed locally. I'm pretty useless w/ HTML/CSS 😆
