### ISSUE TITLE
Code Interface Guide shows "Not Found" after clicking on link

### ISSUE THREAD

**Issue by user1007017** [ash-project/ash_hq#169]
**Show where you found the issue**
A clear and concise description of where the issue is.
https://ash-hq.org/docs/guides/ash/latest/tutorials/get-started.md#what-next-

**Share the problematic documentation**
https://ash-hq.org/documentation/topics/topics/code-interfaces.md

Provide screenshots, or copy and paste the problematic docs
![image](https://github.com/ash-project/ash_hq/assets/2892499/ad1d90eb-5dda-49f2-a3f0-1929673d254b)

**Additional context**
Add any other context about the problem.

**Comment by zachdaniel** [comment]
Fixed, will be updated on the next release of Ash. Thanks!
