### ISSUE TITLE
Link to LiveView section is broken?

### ISSUE THREAD

**Issue by omanuke** [ash-project/ash_hq#188]
In[ this document](https://ash-hq.org/docs/guides/ash_authentication_phoenix/latest/use-ash-authentication-with-liveview),
the link should head for https://ash-hq.org/docs/guides/ash_authentication_phoenix/latest/tutorials/liveview ? Or different place?
<img width="1128" alt="image" src="https://github.com/ash-project/ash_hq/assets/1901757/2d66815d-9895-4522-bbc6-287210c05f9c">

**Comment by zachdaniel** [comment]
Fixed, will be updated on the next package release. Thanks for the report!
