### ISSUE TITLE
Error in iex when running ash-hq locally

### ISSUE THREAD

**Issue by totaltrash** [ash-project/ash_hq#22]
Seeing an error reported in iex when running locally. This is a fresh local install.

- start the server
- open in browser
- click 'get started'
- page loads fine, but the following error is reported in terminal:

[error] Invalid link %Protocol.UndefinedError{description: "", protocol: String.Chars, value: #AshHq.Docs.LibraryVersion<__meta__: #Ecto.Schema.Metadata<:loaded, "library_versions">, __order__: nil, aggregates: %{}, calculations: %{}, extensions: [#AshHq.Docs.Extension<__meta__: #Ecto.Schema.Metadata<:loaded, "extensions">, __order__: nil, aggregates: %{}, calculations: %{}, default_for_target: true, doc: nil, doc_html: nil, dsls: [#AshHq.Docs.Dsl<version_name: "2.0.0-rc.3", search_headline: #Ash.NotLoaded<:calculation>, args: ["validation"], links: %{"guides" => ["ash:guide:Actions"], "modules" => ["ash:module:Ash.Resource.Change"]}, examples: ["validate {Mod, [foo: :bar]}", "validate at_least_one_of_present([:first_name, :last_name])"], extension_id: "626567d7-7d50-42c2-b9c3-f79534551179", id: "cf007ffb-9466-4d38-b3cc-805c474e2ca1", extension_name: "Resource", matches: #Ash.NotLoaded<:calculation>, dsl: #Ash.NotLoaded<:relationship>, aggregates: %{}, doc_html: nil, name: "validate", library_id: "6b5d023e-48b1-43e3-ae7c-efb82eb59a84", extension_order: 0, options: #Ash.NotLoaded<:relationship>, library_version_id: "616bc185-3c4d-4585-8d9d-21d0d7c11230", match_rank: #Ash.NotLoaded<:calculation>, dsls: #Ash.NotLoaded<:relationship>, type: :entity, __order__: nil, calculations: %{}, sanitized_path: "validations/validate", name_matches: #Ash.NotLoaded<:calculation>, library_version: #Ash.NotLoaded<:relationship>, __meta__: #Ecto.Schema.Metadata<:loaded, "dsls">, doc: nil, html_for: #Ash.NotLoaded<:calculation>, dsl_id: nil, order: 0, library_name: "ash", extension: #Ash.NotLoaded<:relationship>, ...>, #AshHq.Docs.Dsl<version_name: "2.0.0-rc.3", search_headline: #Ash.NotLoaded<:calculation>, args: ["preparation"], links: %{"guides" => ["ash:guide:Actions"]}, examples: ["prepare build(sort: [:foo, :bar])"], extension_id: "626567d7-7d50-42c2-b9c3-f79534551179", id: "f3988e6d-5f7a-44cf-9297-853da8937686", extension_name: "Resource", matches: #Ash.NotLoaded<:calculation>, dsl: #Ash.NotLoaded<:relationship>, aggregates: %{}, doc_html: nil, name: "prepare", library_id: "6b5d023e-48b1-43e3-ae7c-efb82eb59a84", extension_order: 0, options: #Ash.NotLoaded<:relationship>, library_version_id: "616bc185-3c4d-4585-8d9d-21d0d7c11230", match_rank: #Ash.NotLoaded<:calculation>, dsls: #Ash.NotLoaded<:relationship>, type: :entity, __order__: nil, calculations: %{}, sanitized_path: "preparations/prepare", name_matches: #Ash.NotLoaded<:calculation>, library_version: #Ash.NotLoaded<:relationship>, __meta__: #Ecto.Schema.Metadata<:loaded, "dsls">, doc: nil, html_for: #Ash.NotLoaded<:calculation>, dsl_id: nil, order: 0, library_name: "ash", ...>, #AshHq.Docs.Dsl<version_name: "2.0.0-rc.3", search_headline: #Ash.NotLoaded<:calculation>, args: ["change"], links: %{"guides" => ["ash:guide:Actions"], "modules" => ["ash:module:Ash.Resource.Change"]}, examples: ["change relate_actor(:reporter)", "change {MyCustomChange, :foo}"], extension_id: "626567d7-7d50-42c2-b9c3-f79534551179", id: "3309fd83-931f-4939-9e51-be618af8b117", extension_name: "Resource", matches: #Ash.NotLoaded<:calculation>, dsl: #Ash.NotLoaded<:relationship>, aggregates: %{}, doc_html: nil, name: "change", library_id: "6b5d023e-48b1-43e3-ae7c-efb82eb59a84", extension_order: 0, options: #Ash.NotLoaded<:relationship>, library_version_id: "616bc185-3c4d-4585-8d9d-21d0d7c11230", match_rank: #Ash.NotLoaded<:calculation>, dsls: #Ash.NotLoaded<:relationship>, type: :entity, __order__: nil, calculations: %{}, sanitized_path: "changes/change", name_matches: #Ash.NotLoaded<:calculation>, library_version: #Ash.NotLoaded<:relationship>, __meta__: #Ecto.Schema.Metadata<:loaded, "dsls">, doc: nil, html_for: #Ash.NotLoaded<:calculation>, dsl_id: nil, order: 0, ...>, #AshHq.Docs.Dsl<version_name: "2.0.0-rc.3", search_headline: #Ash.NotLoaded<:calculation>, args: ["name", "keys"], links: %{"guides" => ["ash:guide:Identities"]}, examples: ["identity :name, [:name]", "identity :full_name, [:first_name, :last_name]"], extension_id: "626567d7-7d50-42c2-b9c3-f79534551179", id: "8302ca73-2828-4613-8b1d-c0709fe9ec2c", extension_name: "Resource", matches: #Ash.NotLoaded<:calculation>, dsl: #Ash.NotLoaded<:relationship>, aggregates: %{}, doc_html: nil, name: "identity", library_id: "6b5d023e-48b1-43e3-ae7c-efb82eb59a84", extension_order: 0, options: #Ash.NotLoaded<:relationship>, library_version_id: "616bc185-3c4d-4585-8d9d-21d0d7c11230", match_rank: #Ash.NotLoaded<:calculation>, dsls: #Ash.NotLoaded<:relationship>, type: :entity, __order__: nil, calculations: %{}, sanitized_path: "identities/identity", name_matches: #Ash.NotLoaded<:calculation>, library_version: #Ash.NotLoaded<:relationship>, __meta__: #Ecto.Schema.Metadata<:loaded, "dsls">, doc: nil, html_for: #Ash.NotLoaded<:calculation>, dsl_id: nil, ...>, #AshHq.Docs.Dsl<version_name: "2.0.0-rc.3", search_headline: #Ash.NotLoaded<:calculation>, args: ["name"], links: %{"guides" => ["ash:guide:Code Interface"]}, examples: ["define :get_user_by_id, action: :get_by_id, args: [:id], get?: true"], extension_id: "626567d7-7d50-42c2-b9c3-f79534551179", id: "b3cc6c2f-5028-42fd-b9ae-9455c54d9f9f", extension_name: "Resource", matches: #Ash.NotLoaded<:calculation>, dsl: #Ash.NotLoaded<:relationship>, aggregates: %{}, doc_html: nil, name: "define", library_id: "6b5d023e-48b1-43e3-ae7c-efb82eb59a84", extension_order: 0, options: #Ash.NotLoaded<:relationship>, library_version_id: "616bc185-3c4d-4585-8d9d-21d0d7c11230", match_rank: #Ash.NotLoaded<:calculation>, dsls: #Ash.NotLoaded<:relationship>, type: :entity, __order__: nil, calculations: %{}, sanitized_path: "code_interface/define", name_matches: #Ash.NotLoaded<:calculation>, library_version: #Ash.NotLoaded<:relationship>, __meta__: #Ecto.Schema.Metadata<:loaded, "dsls">, doc: nil, html_for: #Ash.NotLoaded<:calculation>, ...>, #AshHq.Docs.Dsl<version_name: "2.0.0-rc.3", search_headline: #Ash.NotLoaded<:calculation>, args: ["change"], links: %{"guides" => ["ash:guide:Actions"], "modules" => ["ash:module:Ash.Resource.Change"]}, examples: ["change relate_actor(:reporter)", "change {MyCustomChange, :foo}"], extension_id: "626567d7-7d50-42c2-b9c3-f79534551179", id: "e99c7926-3e8d-49c8-a598-7c016e2e2bef", extension_name: "Resource", matches: #Ash.NotLoaded<:calculation>, dsl: #Ash.NotLoaded<:relationship>, aggregates: %{}, doc_html: nil, name: "change", library_id: "6b5d023e-48b1-43e3-ae7c-efb82eb59a84", extension_order: 0, options: #Ash.NotLoaded<:relationship>, library_version_id: "616bc185-3c4d-4585-8d9d-21d0d7c11230", match_rank: #Ash.NotLoaded<:calculation>, dsls: #Ash.NotLoaded<:relationship>, type: :entity, __order__: nil, calculations: %{}, sanitized_path: "actions/destroy/change", name_matches: #Ash.NotLoaded<:calculation>, library_version: #Ash.NotLoaded<:relationship>, __meta__: #Ecto.Schema.Metadata<:loaded, "dsls">, doc: nil, ...>, #AshHq.Docs.Dsl<version_name: "2.0.0-rc.3", search_headline: #Ash.NotLoaded<:calculation>, args: ["change"], links: %{"guides" => ["ash:guide:Actions"], "modules" => ["ash:module:Ash.Resource.Change"]}, examples: ["change relate_actor(:reporter)", "change {MyCustomChange, :foo}"], extension_id: "626567d7-7d50-42c2-b9c3-f79534551179", id: "6741e884-949e-457f-8585-87ffcf9ccb2c", extension_name: "Resource", matches: #Ash.NotLoaded<:calculation>, dsl: #Ash.NotLoaded<:relationship>, aggregates: %{}, doc_html: nil, name: "change", library_id: "6b5d023e-48b1-43e3-ae7c-efb82eb59a84", extension_order: 0, options: #Ash.NotLoaded<:relationship>, library_version_id: "616bc185-3c4d-4585-8d9d-21d0d7c11230", match_rank: #Ash.NotLoaded<:calculation>, dsls: #Ash.NotLoaded<:relationship>, type: :entity, __order__: nil, calculations: %{}, sanitized_path: "actions/update/change", name_matches: #Ash.NotLoaded<:calculation>, library_version: #Ash.NotLoaded<:relationship>, __meta__: #Ecto.Schema.Metadata<:loaded, "dsls">, ...>, #AshHq.Docs.Dsl<version_name: "2.0.0-rc.3", search_headline: #Ash.NotLoaded<:calculation>, args: ["name", "type"], links: %{}, examples: ["argument :password_confirmation, :string"], extension_id: "626567d7-7d50-4 (truncated)

**Comment by zachdaniel** [comment]
This isn't so much an error, just that there was something in the docs that couldn't be "hydrated" and should be fixed in the docs.

So if we see these it means something is referring to a non-existent thing.
