### ISSUE TITLE
Top bar has gaps on both sides on mobile 

### ISSUE THREAD

**Issue by joelpaulkoch** [ash-project/ash_hq#242]
**Brief Description**

The sticky top bar leaves gaps open on each side.

**Steps to reproduce the bug**

Open ash HQ on mobile e.g. [here](https://ash-hq.org/docs/guides/ash_phoenix/latest/tutorials/getting-started-with-ash-and-phoenix#connecting-your-resource-to-a-phoenix-liveview)

**Context**
I'm on an Asus Zenfone 10 using Firefox.

Screenshot:

![Screenshot_20240831-103729_ASUS_Launcher.jpg](https://github.com/user-attachments/assets/850f9123-ef9c-4b58-9242-1f3ebd7bab64)

**Comment by zachdaniel** [comment]
Thank you for the report! This should be fixed now :)
