### ISSUE TITLE
js collapsable sidebar

### ISSUE THREAD

**Issue by zachdaniel** [ash-project/ash_hq#33]
Need to improve the general behavior of the sidebar, and make all expansion/selection state client-side.

**Comment by mbuhot** [comment]
I can take a look into this one @zachdaniel.
Are there any public examples that can serve as a reference for what you have in mind?

**Comment by zachdaniel** [comment]
Nothing comes to mind really, but I think the idea is to have it behave pretty much like a file tree, where the open element is always expanded to, and is highlighted.
