### ISSUE TITLE
Incorrect headings when navigating between particular pages

### ISSUE THREAD

**Issue by mbuhot** [ash-project/ash_hq#38]
**Brief Description**

Navigating from https://ash-hq.org/docs/guides/ash_postgres/1.1.1/topics/polymorphic_resources.md to https://ash-hq.org/docs/guides/ash_postgres/1.1.1/topics/migrations_and_tasks.md via the tree-view results in the "Migrations" heading appears both as a `<h1>` and as a `<h2>` (see image).

**Steps to reproduce the bug**

On MacOS Safari visit https://ash-hq.org/docs/guides/ash_postgres/1.1.1/topics/polymorphic_resources.md
Click the Guides -> Topics -> Ash Postgres -> Migrations and Tasks link in the tree view
Notice the header is incorrect.
Refresh the page and it displays correctly.

**Context**

<img width="1471" alt="image" src="https://user-images.githubusercontent.com/336840/198517948-a4732f75-6c2b-4323-b79e-6cae7147e449.png">

Perhaps it is related to both pages having a DOM element with id="migrations" ?

**Comment by mbuhot** [comment]
Looks like this is actually a bug in morphdom: https://github.com/patrick-steele-idem/morphdom/pull/231

I'll see if there's a workaround without the performance hit of replacing `<LivePatch>` with `<LiveRedirect>`

**Comment by zachdaniel** [comment]
Wow, great digging! If we *have* to use `<LiveRedirect>` it won't be horrible, but definitely worth looking for a different workaround. We could potentially prefix the ids with some unique string when building the markdown html?

**Comment by mbuhot** [comment]
Yes unique IDs will solve it. We could generate a unique prefix based on a hash of the page title/content or even just the heading level, so that we'd have `h1-migrations` and `h2-migrations`.

**Comment by zachdaniel** [comment]
Every version of everything has a uuid, so we should be able to just use that as a prefix when generating the HTML.

**Comment by zachdaniel** [comment]
If we thread through the UUID of the thing we're rendering all the way down to here: https://github.com/ash-project/ash_hq/blob/main/lib/ash_hq/docs/extensions/render_markdown/render_markdown.ex#L115, then we can prefix all the ids with that.

**Comment by mbuhot** [comment]
Thanks @zachdaniel, I'll create a PR today 👍
