### ISSUE TITLE
Search results should prioritize exact matches

### ISSUE THREAD

**Issue by sevenseacat** [ash-project/ash_hq#42]
**Brief Description**
eg. when searching for `load`, I'd expect exact matches for functions named `load` to be first in the results.

<img width="1121" alt="Screen Shot 2022-11-01 at 11 05 00 am" src="https://user-images.githubusercontent.com/543859/199149841-b59e3f5f-a397-4bde-a021-095627b4c757.png">

(The first exact match, the function `Ash.Api.load`, is the thirteenth result in the search)

**Comment by zachdaniel** [comment]
Exact matches will now always be shown at the top, followed by anything that matches on name sorted by length ascending, followed by everything else. Thanks for the report!
