### ISSUE TITLE
Anchors for functions/etc. cause page jiggling on scroll (Firefox)

### ISSUE THREAD

**Issue by sevenseacat** [ash-project/ash_hq#43]
**Brief Description**

Using OSX and Firefox - it doesn't happen in Safari or Chrome.

Scrolling past a certain point on any page seems to give a weird jiggling effect every time an anchor is passed - like its trying to snap to the anchor or something?

eg. on https://ash-hq.org/docs/module/ash/2.4.0/ash-type

https://user-images.githubusercontent.com/543859/199183512-a15ae10e-2f55-4de7-9fb2-80e61c7826a2.mov

**Comment by zachdaniel** [comment]
🤮
