### ISSUE TITLE
Docs and sidebar partially hidden when URL includes certain fragment identifiers

### ISSUE THREAD

**Issue by mbuhot** [ash-project/ash_hq#46]
**Brief Description**

Certain links, such as: https://ash-hq.org/docs/guides/ash/latest/topics/aggregates#custom-aggregates-in-the-query cause the top of the docs and sidebar to be hidden behind the top-bar.

**Steps to reproduce the bug**

click: https://ash-hq.org/docs/guides/ash/latest/topics/aggregates#custom-aggregates-in-the-query
Scroll to top
Notice the `<h1>` isn't visible.
Notice the top of the sidebar isn't visible, so you can't toggle the visible packages until you refresh the page.

**Context**

<img width="1945" alt="image" src="https://user-images.githubusercontent.com/336840/200229885-bc8703d9-d461-49ad-86c8-58e7c0f2f461.png">

<img width="1941" alt="image" src="https://user-images.githubusercontent.com/336840/200230072-3d804031-ad82-4c3a-91ce-7ffd92da6f87.png">

**Comment by zachdaniel** [comment]
huh...this is definitely strange...perhaps we need to do something like "if it is already visible, don't scroll to it" or something? Honestly this kind of thing is not my forte :(

**Comment by mbuhot** [comment]
I'll look into it @zachdaniel. After some googling, it seems the recommended fix for this problem is to add a CSS rule like:

```css
:target {
  scroll-margin-top: 80px;
}
```

Which stops content being scrolled by the browser from being positioned behind a sticky header.
There's some complications with Ash HQ due to the 3 column layout where the docs content has it's own scrollbar.

An example I found of a docs site that has a nice 3 column layout with working link fragments is MDN, eg https://developer.mozilla.org/en-US/docs/Web/CSS/:target#see_also

Would you be open to adjusting the layout so that the main docs content scrolls with the window top level scrollbar?

**Comment by zachdaniel** [comment]
Totally up for changing the layout :)
