### ISSUE TITLE
404 without sufficient redirect

### ISSUE THREAD

**Issue by SupaMic** [ash-project/ash_hq#49]
**Show where you found the issue**
Bottom of page: https://ash-hq.org/docs/guides/ash/2.4.2/topics/multitenancy
In the sentence:  "For AshPostgres context multitenancy, which uses postgres schemas, see the **guide**"
The word **guide** links to [guide](https://hexdocs.pm/ash_postgres/multitenancy.html)

**Share the problematic documentation**
This 404's, PAGE NOT FOUND in Hexdocs.pm

**Additional context**
Should probably link to https://hexdocs.pm/ash_postgres/schema-based-multitenancy.html
Although this does not exactly describe "context multitenancy"

**Comment by zachdaniel** [comment]
Thanks for the report! I've been on vacation, so apologies for the slow response. I've resolved this and it will be fixed on the next version release of ash. Thanks again :)

**Comment by SupaMic** [comment]
Hope you had a great vacation!
