### ISSUE TITLE
Package filter resets when selecting a search result

### ISSUE THREAD

**Issue by sevenseacat** [ash-project/ash_hq#52]
**Brief Description**

Just came across this - makes it really hard to use consistently for multiple packages! I always want to have Ash and AshPhoenix selected as active packages.

**Steps to reproduce the bug**

* Visit ash-hq.org
* Under "Selected Packages" in left sidebar, select some stuff (eg. Ash and AshPhoenix latest)
* Use big "Search documentation" search bar at top of screen
* Search for something within Ash, eg. `changeset`
* Click first search result (which for me in this case is Ash.Generator.changeset, make sure it's something within the Ash package)
* Page reloads at the selected result, eg. https://www.ash-hq.org/docs/module/ash/latest/ash-generator/#function-changeset-4
* "Selected Packages" now resets to only be "ash | 2.4.2"

**Comment by zachdaniel** [comment]
woof, definitely an issue. That is the whole point of that selector! I will take a look in the AM. Do you know if you enabled/disabled the cookie storage? We store that info in the cookie as well as the liveview state, and I'm wondering if that is coming into play here.

**Comment by sevenseacat** [comment]
I've tested with both no cookie state (having the banner at the bottom of the page), pressing "Got it!", and pressing "Allow cookies" (though I don't know what the difference between the options is, that's a separate issue though.) Happens in all three cases.

**Comment by sevenseacat** [comment]
Another example:

* Have AshPhoenix and some other packages (but NOT ash main) selected
* Search for something in AshPhoenix (eg. FilterForm)
* Click first search result
* Selected packages are now `ash` and `ash_phoenix` instead of AshPhoenix + other non-ash packages

**Comment by zachdaniel** [comment]
Very bad :) I'll get this addressed ASAP as its a major usability impact.

**Comment by zachdaniel** [comment]
Looks like this actually relates to this: https://stackoverflow.com/questions/74095764/live-redirect-doesnt-grab-session-correctly

I can see why this behavior works this way, it has something to do with the fact that we "re-mount" on a live redirect without going through the process of getting the session from the conn. Still investigating how to fix it :)

**Comment by zachdaniel** [comment]
Fixed here: 5ed98bf5a90eafd9a67640df27dc128248ddcde1
