### ISSUE TITLE
Default values for options missing

### ISSUE THREAD

**Issue by totaltrash** [ash-project/ash_hq#60]
**Show where you found the issue**
The reference section on ash hq doesn't display the default values for options. For instance:

https://ash-hq.org/docs/dsl/ash/2.4.16/resource/relationships/belongs_to#allow_nil-:

![image](https://user-images.githubusercontent.com/637350/204929537-6ed4853b-6389-4f04-86ff-5226383f5ab1.png)

The default values are displayed on hexdocs:

![image](https://user-images.githubusercontent.com/637350/204929446-84ca7c40-f403-427f-ad48-c3f90c06ad02.png)

I feel like we need another column in the table for the default value (rather than embedding the default value into the description)

**Comment by zachdaniel** [comment]
Oh, wow you're absolutely correct! I'll add a default value before the description now :)

**Comment by zachdaniel** [comment]
deploying a fix for this now.
