### ISSUE TITLE
Output is blank for Ash Postgres Tutorial in Dark Mode

### ISSUE THREAD

**Issue by juddey** [ash-project/ash_hq#62]
**Brief Description**

Viewing Docs at ash-hq.org

**Steps to reproduce the bug**
Activate Dark Mode in MacOS or Linux
Navigate to https://ash-hq.org/docs/guides/ash_postgres/latest/ashpostgres 

The blue topbar runs, but no content is displayed.

Specifically tested on: Linux/Firefox & MacOS /Safari dark modes.

**Context**
Content failing to display in dark mode in FF Linux
![image](https://user-images.githubusercontent.com/7445602/208016869-7c9944ba-6722-4f98-985b-44754918bd63.png)

Note this does not occur in light mode (could only test on Chrome/Linux)
![image](https://user-images.githubusercontent.com/7445602/208018281-7fc6f25e-b391-4a71-9e18-ca65f86750dc.png)

I guess the first question is, can we replicate in Google Chrome's dark mode on MacOS?

**Comment by zachdaniel** [comment]
Could you check again? I think this may have just been a temporary issue while we were deploying.

**Comment by zachdaniel** [comment]
I don't think dark mode could have any effect here because its all CSS driven, nothing on the app side knows about dark mode really.

**Comment by juddey** [comment]
Yep, I tried again this morning, still no output. (Linux/FF and MacOS - Safari/Chrome)

I can have a look into it Monday if I get the time.

**Comment by zachdaniel** [comment]
Could you try clearing your browser cookies for the site?

**Comment by zachdaniel** [comment]
Ah, I see what happened. That link is bad. I think you made another docs PR that fixed that link, so it should be unreachable now.

**Comment by juddey** [comment]
Nope, I didn't change _that_ link. Got things working today locally though and I think its meant to point here:
https://ash-hq.org/docs/guides/ash_postgres/latest/tutorials/get-started-with-postgres

Noting for fixing tomorrow (or posterity, if I don't get to it due to new clients. :)

**Comment by zachdaniel** [comment]
Yeah, I think so. Do you remember how you got there?

**Comment by juddey** [comment]
Yeah, I do, and I'll try and fix it today.
