### ISSUE TITLE
Code snippets don't have syntax higlighting

### ISSUE THREAD

**Issue by Darth-Knoppix** [ash-project/ash_hq#64]
**Brief Description**

Code snippets don't have syntax highlighting.

As far as I can tell, this isn't an issue with a specific package, it occurs across all related Ash packages. There appears to be relevant classes associated with each `<code>` element e.g. `bash` or `elixir` but there is no styling applied, just white text on a sark grey background.

**Steps to reproduce the bug**

1. Visit a documentation page with a code block present. e.g. https://www.ash-hq.org/docs/guides/ash/latest/tutorials/get-started#add-ash-to-your-application
2. Notice the code blocks have no syntax highlighting. 

**Context**

Here's an example of a code block taken from [here](https://www.ash-hq.org/docs/guides/ash/latest/tutorials/get-started#add-ash-to-your-application)

<img width="699" alt="Screenshot 2022-12-23 at 16 17 56" src="https://user-images.githubusercontent.com/2019236/209366290-99078c27-3239-4763-8cf5-3046ddd04351.png">

**Comment by Darth-Knoppix** [comment]
Note: Not sure if this is a bug or an enhancement.

**Comment by minibikini** [comment]
I also suffer because of this and often switch to `hexdocs.pm`.

**Comment by zachdaniel** [comment]
I believe this is something that must have broken recently. I'll take a look :)

**Comment by zachdaniel** [comment]
This has been handled, and newly imported versions will have proper highlighting.
