### ISSUE TITLE
Broken Link from Pagination guide

### ISSUE THREAD

**Issue by dantswain** [ash-project/ash_hq#65]
In the first paragraph here: https://www.ash-hq.org/docs/guides/ash/latest/topics/pagination#pagination
The `[actions > read > prepare](https://www.ash-hq.org/docs/dsl/ash/latest/actions/read/prepare)` link results in an "Internal Server Error" page.

Also as a minor note, it would be really nice to include an example of actually incorporating pagination into an action on this page.

**Comment by zachdaniel** [comment]
For improving the contents of the docs themselves, issues or PRs to the relevant project (in this case Ash) are welcome :D This guide can be found in `/documentation/topics`. For the issue with a broken link, I'm pushing a fix currently.

**Comment by zachdaniel** [comment]
Thanks for the report!
