### ISSUE TITLE
Search box usability issue

### ISSUE THREAD

**Issue by dantswain** [ash-project/ash_hq#66]
This is debatable but this has tripped me up many times so far.

1. Search for anything using the search bar.
2. Click any of the links, which takes you to that page and dismisses the search bar.
3. Click the search bar again, the previously-entered search term is still entered in the box and the cursor is at the end of that string as if you were going to continue typing at the end of that term.

I generally expect to be able to click a search bar and start typing a _new_ search term.  E.g., if I search for `limit` and then view the results, then some time later I come back to the same tab in my browser and want to search for, say, `constraints` and my instinct is to click the search bar and start typing `constraints` but with the current behavior this results in `limitconstraints` in the search bar.

I can see it being helpful to keep the same search results for the "hmm that result wasn't helpful, let me try one of the other results", so maybe a compromise would be to bring up the modal with the previous text but have the text highlighted so that if the user starts typing, it replaces the existing text by default?

**Comment by zachdaniel** [comment]
Yeah, that is a good point :) I think the simplest answer would be to clear out the search bar, which I've added. There is still some weird behavior I haven't figured out WRT the search typeahead and navigation behaving a bit different on the first navigation if used from the home page. Don't know whats up there yet, unfortunately. But it works every other time 😆 I'll close this for now since it is "mostly" solved.

**Comment by zachdaniel** [comment]
Thanks for the report!

**Comment by dantswain** [comment]
@zachdaniel Thanks for taking action so quickly!  I'm not sure the change is behaving as intended, though?  Now what I see is that when I click the search bar again, the _text_ is still there but none of the previous search results are present.  This is the opposite of what I thought you meant.

**Comment by zachdaniel** [comment]
🤔 this may be the quirky behavior I mentioned where it behaves that way only on the first time when using it from the home page. Do you still see that behavior if you click into the documentation and use it from there? You're right though, I did also end up clearing the search results which isn't ideal.

**Comment by dantswain** [comment]
Yeah it's still basically the same as before for me except now it clears the search results.  Doesn't seem to matter which page I'm on or how many times I use it.
