### ISSUE TITLE
Documenataion site refreshing every 30 seconds

### ISSUE THREAD

**Issue by corepay** [ash-project/ash_hq#81]
Excited to look into Ash

https://ash-hq.org/docs/guides/ash/latest/tutorials/get-started or any page for that matter is refreshing every 30 seconds or so.  

FYI i am using a slow 3g mobile network if that matters.

**Comment by zachdaniel** [comment]
TBH still haven't been able to figure this out. We've made lots of changes including dependency updates, might be worth checking again?

**Comment by sevenseacat** [comment]
I can replicate this in Chrome if I set network throttling to slow 3G. Not sure what causes it yet, perhaps a websocket timeout.

<img width="971" alt="Screenshot 2023-02-01 at 3 03 36 pm" src="https://user-images.githubusercontent.com/543859/215974148-db26bd2a-55c9-448f-99cd-764d49b06d3b.png">

**Comment by zachdaniel** [comment]
This is probably just a drawback of using LiveView for this, but I imagine there are mitigation strategies?

**Comment by sevenseacat** [comment]
The app.js file is 500kB, which is slow to load. And if the websocket timeout is counting from the start of the page load, and its low, then I can imagine weirdness happening. Not sure why the page would reload though - I would have thought the page would stop responding to LV events.

<img width="1495" alt="Screenshot 2023-02-01 at 3 12 36 pm" src="https://user-images.githubusercontent.com/543859/215975831-55eb61ef-a78e-40df-b7a3-833e4dac81ca.png">

**Comment by sevenseacat** [comment]
We've done some work with lightening the JS load and using more efficient LiveView navigation - can you check and see if its still an issue for you? I can't replicate it any more.

**Comment by corepay** [comment]
Oh hey, sorry been away for a while.  I'm no longer in 3G territory and have high-speed internet here.  Everything looks good here from now but have no way to check using the network I used when encountering the OG issue.
