### ISSUE TITLE
Ash autocomplete plugin install doc bug?

### ISSUE THREAD

**Issue by joevandyk** [ash-project/ash_hq#93]
I'm unsure if there's another unmentioned step to install the autocomplete vscode plugin, or if there's no changes needed if you add the ash dependency (in which case, why should it be called out again here?)

![image](https://user-images.githubusercontent.com/1179/218276936-96721e0a-0da4-4944-abce-68b865aa2264.png)

**Comment by zachdaniel** [comment]
oops :D That is old instructions that weren't properly removed in their entirety. I'll remove them and it will update on the next deploy.

**Comment by zachdaniel** [comment]
Fixed in the repo, reimporting docs now :). Thanks for the report!
