### ISSUE TITLE
AshPhoenix and AshPostgres should be enabled by default when viewing the documentation

### ISSUE THREAD

**Issue by sevenseacat** [ash-project/ash_hq#98]
At the moment only Ash is enabled by default, but in the majority of cases, new users will be using all three of the libraries and may get tripped up on how to enable the others.

Have seen this internally even after the addition of the Big Blue Box - user asking why the documentation for AshPhoenix is missing on AshHQ, not realizing it needed to be enabled first.

**Comment by zachdaniel** [comment]
Completed in b00d56b5c236f695d52a54a5b742a8bcb555dbd8

**Comment by sevenseacat** [comment]
❤️ 💛 💚 💙 💜
