### ISSUE TITLE
Nested DSL options should be combined into one page

### ISSUE THREAD

**Issue by sevenseacat** [ash-project/ash_hq#99]
eg. having one page for `Ash.Resource.Dsl -> relationships` instead of separate pages for `Ash.Resource.Dsl -> relationships -> has_many` and `Ash.Resource.Dsl -> relationships -> has_one`

**Comment by zachdaniel** [comment]
We can take it even further and just have it all in one page for `Ash.Resource.DSL`

**Comment by zachdaniel** [comment]
I.e one page for each dsl/extension.

**Comment by sevenseacat** [comment]
it has been done!
